"""Persistence layer: declarative base, mapped models, column types and session management.

Importing this package imports :mod:`autotwin_core.db.models`, which is what registers every
table on ``Base.metadata``. Alembic's ``env.py`` relies on that — a model module that is never
imported is a table that silently disappears from the next autogenerated migration.

Nothing here opens a connection at import time; engines are created lazily by
:mod:`autotwin_core.db.session`.
"""

from __future__ import annotations

from autotwin_core.db.base import (
    NAMING_CONVENTION,
    Base,
    CreatedAtMixin,
    TimestampMixin,
    UUIDPrimaryKeyMixin,
    model_repr,
)
from autotwin_core.db.mixins import ProvenanceMixin
from autotwin_core.db.models import (
    ChargingPoint,
    ChargingStation,
    DataIngestionRun,
    MLModel,
    MLPrediction,
    Route,
    RouteSegment,
    SimulationRun,
    Telemetry,
    TrafficEvent,
    Trip,
    Vehicle,
    VehicleModel,
    WeatherObservation,
    WeatherStation,
)
from autotwin_core.db.session import (
    check_database,
    dispose_engine,
    get_engine,
    get_session,
    get_sessionmaker,
    get_sync_engine,
    session_scope,
)
from autotwin_core.db.types import (
    JSONBDict,
    LineStringGeometry,
    PointGeography,
    from_wkb_linestring,
    from_wkb_point,
    to_shape_linestring,
    to_shape_point,
)

__all__ = [
    "NAMING_CONVENTION",
    "Base",
    "ChargingPoint",
    "ChargingStation",
    "CreatedAtMixin",
    "DataIngestionRun",
    "JSONBDict",
    "LineStringGeometry",
    "MLModel",
    "MLPrediction",
    "PointGeography",
    "ProvenanceMixin",
    "Route",
    "RouteSegment",
    "SimulationRun",
    "Telemetry",
    "TimestampMixin",
    "TrafficEvent",
    "Trip",
    "UUIDPrimaryKeyMixin",
    "Vehicle",
    "VehicleModel",
    "WeatherObservation",
    "WeatherStation",
    "check_database",
    "dispose_engine",
    "from_wkb_linestring",
    "from_wkb_point",
    "get_engine",
    "get_session",
    "get_sessionmaker",
    "get_sync_engine",
    "model_repr",
    "session_scope",
    "to_shape_linestring",
    "to_shape_point",
]
