"""Declarative base, naming convention and the primary-key / timestamp mixins.

``alembic/env.py`` targets :class:`Base` — every table in the project is reachable from
``Base.metadata``, and nothing creates tables at application startup (BUILD_SPEC §3.3).

The explicit naming convention is what makes Alembic autogenerate usable over the life of the
project. Without it PostgreSQL invents constraint names (``charging_points_station_id_fkey``)
that differ from the names SQLAlchemy expects, and every autogenerated migration starts
proposing spurious drops and re-creates of constraints that never changed.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any, ClassVar, Final
from uuid import UUID, uuid4

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

__all__ = [
    "NAMING_CONVENTION",
    "Base",
    "CreatedAtMixin",
    "TimestampMixin",
    "UUIDPrimaryKeyMixin",
    "model_repr",
]

NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}
"""Deterministic constraint names, so a migration diff only ever contains real changes."""

_ID_SORT_ORDER: Final[int] = -100
"""Keeps ``id`` the first column of every ``CREATE TABLE``, whatever the mixin order is."""

_AUDIT_SORT_ORDER: Final[int] = 100
"""Keeps the audit timestamps last, after the columns that carry domain meaning."""


class Base(DeclarativeBase):
    """Declarative base of every AutoTwin table.

    The ``type_annotation_map`` fixes the Python-to-PostgreSQL mapping once, centrally, in the
    terms BUILD_SPEC §3 uses: ``str`` is ``TEXT`` (the spec says *text*, and PostgreSQL makes
    no performance distinction), ``float`` is ``DOUBLE PRECISION`` (physical quantities and
    percentages), ``datetime`` is ``TIMESTAMP WITH TIME ZONE`` (never naive, always UTC) and a
    JSON object column is ``JSONB``. Models therefore only spell a column type out when it
    deviates — enums, geometry, ``BIGINT`` keys.
    """

    metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map: ClassVar[dict[Any, Any]] = {
        bool: sa.Boolean(),
        int: sa.Integer(),
        float: postgresql.DOUBLE_PRECISION(),
        str: sa.Text(),
        datetime: sa.TIMESTAMP(timezone=True),
        date: sa.Date(),
        UUID: postgresql.UUID(as_uuid=True),
        dict[str, Any]: postgresql.JSONB(),
        list[str]: postgresql.JSONB(),
    }


class UUIDPrimaryKeyMixin:
    """A ``UUID`` primary key generated by the application (BUILD_SPEC §3).

    Application-side ``uuid4`` rather than a database default: an ingestion pipeline builds a
    whole batch of rows — parent stations and their child charging points — in memory and needs
    the parent's key before any of it reaches PostgreSQL, and a bulk insert must not have to
    round-trip for generated keys.
    """

    id: Mapped[UUID] = mapped_column(
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        sort_order=_ID_SORT_ORDER,
    )


class CreatedAtMixin:
    """A single ``created_at`` stamp, for rows that are written once and never updated."""

    created_at: Mapped[datetime] = mapped_column(
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        sort_order=_AUDIT_SORT_ORDER,
    )


class TimestampMixin(CreatedAtMixin):
    """``created_at`` plus an ``updated_at`` maintained on every UPDATE.

    Both defaults are *server* side so that rows written by a migration, by ``psql`` or by a dbt
    model carry the same stamps as rows written through the ORM; ``onupdate`` additionally keeps
    the ORM path correct for partial updates.
    """

    updated_at: Mapped[datetime] = mapped_column(
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        onupdate=sa.func.now(),
        sort_order=_AUDIT_SORT_ORDER + 1,
    )


def model_repr(instance: object, *attributes: str) -> str:
    """Render ``ClassName(attr=value, ...)`` for a mapped instance.

    Used by every model's ``__repr__``. Attributes that are not loaded — a lazy relationship or
    a deferred column on a detached instance — render as ``<unloaded>`` instead of triggering a
    lazy load, because a ``repr`` that emits SQL turns a debugger session or an error log into
    a source of new exceptions.
    """
    parts: list[str] = []
    for name in attributes:
        try:
            value = getattr(instance, name)
        # A repr must never raise, whatever state the ORM instance is in.
        except Exception:
            parts.append(f"{name}=<unloaded>")
        else:
            parts.append(f"{name}={value!r}")
    return f"{type(instance).__name__}({', '.join(parts)})"
