"""``/api/v1/ml`` — the model registry, its evidence, and predictions with their attribution.

Two stores describe the same models and both are read here. The **models directory** is the
serving truth: the artefact and its ``*.metrics.json`` sidecar are what can actually answer a
request. The **``ml_models`` table** is the queryable truth, and is what carries the row id the
frontend selects on. ``GET /ml/models`` prefers the table and falls back to the directory with a
deterministic id, so a freshly cloned repository — artefacts committed, database empty — still
lists its models instead of claiming none exist.

Metrics are **read**, never recomputed. The numbers in the sidecar are the ones the model was
evaluated with, on the split it was evaluated on; an endpoint that re-scored on request would
quietly report a different test set every time the training data changed.

Nothing trained yet answers **503 `configuration_missing`** — the same code the copilot uses for
"this deployment is not configured for that". The registry raises the condition as
``ModelNotAvailable`` (503 ``model_not_available``); it is remapped here so a client has one
code to switch on for the whole family, and the message always names the command that fixes it.
"""

from __future__ import annotations

import asyncio
from collections.abc import Sequence
from typing import Annotated, Any, ClassVar, Final
from uuid import NAMESPACE_URL, UUID, uuid5

import sqlalchemy as sa
from fastapi import APIRouter, Query

from autotwin_api.deps import DbSession
from autotwin_api.schemas.ml import (
    FeatureImportanceEntry,
    GlobalShapEntry,
    GlobalShapReportOut,
    MetricsBlock,
    MLMetrics,
    MLModelInfo,
    PredictedVsActual,
    PredictRequest,
    PredictResponse,
    ResidualBucket,
    ShapContribution,
)
from autotwin_contracts import DataOrigin, VehicleProfile, utc_now
from autotwin_core.db.models import MLModel, VehicleModel
from autotwin_core.errors import AutoTwinError, NotFoundError
from autotwin_core.logging import get_logger
from autotwin_ml.inference import EnergyPredictor, Prediction, record_prediction
from autotwin_ml.registry import ModelNotAvailable, ModelRecord, discover_models, resolve_model
from autotwin_ml.types import SegmentConditions

__all__ = ["router"]

_LOGGER = get_logger(__name__)

router = APIRouter()

_MODEL_ID_NAMESPACE: Final[str] = "https://autotwin.de/ml-models/"
"""Namespace for the deterministic id of an artefact that has no registry row yet.

Deterministic rather than random so that the id the frontend selected before a restart still
names the same version afterwards.
"""

_RESIDUAL_BINS: Final[int] = 25
"""Bins in the residual histogram. Enough to show skew and bimodality on a 400-point test
sample without leaving most bins empty."""

_MAX_SCATTER_POINTS: Final[int] = 500
"""Points returned for the predicted-vs-actual scatter. Beyond this the plot is a blob and the
payload is the dominant cost of the `/ml` page."""

_TRAINING_DATA_NOTE: Final[str] = (
    "Trained on telemetry generated by this platform's own physics model. These metrics "
    "demonstrate that the pipeline — features, training, evaluation against a physical "
    "baseline, SHAP attribution — is sound. They say nothing about a real vehicle on a real "
    "road (BUILD_SPEC §10.2)."
)


class ModelNotTrainedError(AutoTwinError):
    """No model artefact is available to serve.

    503 rather than 404: the resource is not missing, the deployment is not configured to serve
    it yet, and a client that retries after ``python -m autotwin_ml.cli train`` will succeed.
    """

    code: ClassVar[str] = "configuration_missing"
    http_status: ClassVar[int] = 503


def _model_id(name: str, version: str) -> UUID:
    """Deterministic id for a model version that exists on disk but not in ``ml_models``."""
    return uuid5(NAMESPACE_URL, f"{_MODEL_ID_NAMESPACE}{name}/{version}")


def _info_from_row(row: MLModel) -> MLModelInfo:
    """Project an ``ml_models`` row onto the registry payload."""
    return MLModelInfo(
        id=row.id,
        name=row.name,
        version=row.version,
        algorithm=row.algorithm,
        trained_at=row.trained_at,
        training_rows=row.training_rows,
        feature_names=[str(value) for value in row.feature_names],
        is_active=row.is_active,
        training_data_origin=row.training_data_origin,
        notes=row.notes,
    )


def _info_from_record(record: ModelRecord) -> MLModelInfo:
    """Project an on-disk artefact onto the registry payload."""
    return MLModelInfo(
        id=_model_id(record.name, record.version),
        name=record.name,
        version=record.version,
        algorithm=record.algorithm,
        trained_at=record.trained_at,
        training_rows=record.training_rows,
        feature_names=list(record.feature_names),
        is_active=record.is_active,
        training_data_origin=record.training_data_origin,
        notes=record.notes,
    )


async def _resolve(version: str | None, name: str | None) -> ModelRecord:
    """Resolve a model version off disk, in a worker thread, as a 503 when there is none.

    Resolution touches the filesystem, so it runs through :func:`asyncio.to_thread` rather than
    blocking the event loop for every other request in flight.
    """
    try:
        return await asyncio.to_thread(resolve_model, version, name=name)
    except ModelNotAvailable as exc:
        raise ModelNotTrainedError(exc.message, details=dict(exc.details)) from exc


def _residual_histogram(
    values: Sequence[float], *, bins: int = _RESIDUAL_BINS
) -> list[ResidualBucket]:
    """Bin raw residuals into a histogram of bin centres and counts.

    The sidecar stores the residuals themselves — which is the right thing to store, because a
    histogram cannot be re-binned — so the binning happens here. The range is symmetric about
    zero so that an unbiased model's histogram is visibly centred rather than merely appearing
    to be, and a lopsided range is exactly what would hide a bias.
    """
    finite = [float(value) for value in values if value == value]  # NaN != NaN
    if not finite:
        return []
    extent = max(abs(min(finite)), abs(max(finite)))
    if extent <= 0.0:
        return [ResidualBucket(bucket=0.0, count=len(finite))]

    width = 2 * extent / bins
    counts = [0] * bins
    for value in finite:
        index = int((value + extent) / width)
        counts[min(max(index, 0), bins - 1)] += 1
    return [
        ResidualBucket(bucket=-extent + width * (index + 0.5), count=count)
        for index, count in enumerate(counts)
    ]


def _as_float(value: Any) -> float:
    """Coerce a number read out of the metrics sidecar, defaulting a missing one to zero.

    The sidecar is a file on disk, not a validated payload: a malformed entry should cost one
    bar of a chart, not the whole ``/ml`` page.
    """
    return float(value) if isinstance(value, int | float) and not isinstance(value, bool) else 0.0


def _feature_importance(metrics: dict[str, Any]) -> list[FeatureImportanceEntry]:
    """Global importance, preferring SHAP over the tree's own split gain.

    Mean |SHAP| is in the units of the target and is comparable across models; split gain is
    biased towards high-cardinality features and is not. The gain is used only when the SHAP
    block is missing, which happens when the explainer degraded during training.
    """
    shap_block = metrics.get("shap")
    if isinstance(shap_block, dict):
        entries = shap_block.get("global_importance")
        if isinstance(entries, list) and entries:
            return [
                FeatureImportanceEntry(
                    feature=str(entry.get("feature", "")),
                    importance=_as_float(entry.get("mean_abs_shap")),
                    label_de=entry.get("label_de"),
                    label_en=entry.get("label_en"),
                )
                for entry in entries
                if isinstance(entry, dict)
            ]

    gains = metrics.get("feature_importance")
    if not isinstance(gains, list):
        return []
    return [
        FeatureImportanceEntry(
            feature=str(entry.get("feature", "")),
            importance=_as_float(entry.get("importance_normalised", entry.get("importance"))),
        )
        for entry in gains
        if isinstance(entry, dict)
    ]


@router.get(
    "/models",
    response_model=list[MLModelInfo],
    summary="Trained model versions",
    description=(
        "Every version this deployment knows, newest training run first.\n\n"
        "Read from the `ml_models` table; when that is empty — a fresh clone whose artefacts "
        "are committed but whose database has just been migrated — the models directory is "
        "listed instead, with a deterministic id derived from name and version.\n\n"
        "Every model here was trained on **simulated** labels."
    ),
)
async def list_models(session: DbSession) -> list[MLModelInfo]:
    """List registered versions, falling back to the artefacts on disk."""
    rows = (
        (await session.execute(sa.select(MLModel).order_by(MLModel.trained_at.desc())))
        .scalars()
        .all()
    )
    if rows:
        return [_info_from_row(row) for row in rows]

    records = await asyncio.to_thread(discover_models)
    if records:
        _LOGGER.info("ml.models.from_disk", count=len(records))
    return [_info_from_record(record) for record in records]


@router.get(
    "/metrics",
    response_model=MLMetrics,
    summary="Model card and evaluation",
    description=(
        "The model card together with everything the `/ml` page plots: the six headline scores "
        "for **both** the learned model and the physical baseline on the same held-out test "
        "set, a sample of predicted-vs-actual points, the residual histogram and global "
        "feature importance.\n\n"
        "The numbers are read from the metrics file training wrote, never recomputed, so they "
        "always describe the split the model was actually evaluated on."
    ),
)
async def model_metrics(
    session: DbSession,
    model: Annotated[
        str | None,
        Query(description="Model name; defaults to `AUTOTWIN_ML_ACTIVE_MODEL`."),
    ] = None,
    version: Annotated[
        str | None,
        Query(description="Version; defaults to the active one."),
    ] = None,
) -> MLMetrics:
    """Read one version's metrics sidecar and shape it for the evaluation page.

    Raises:
        ModelNotTrainedError: Nothing is trained, or the requested version does not exist —
            ``503 configuration_missing``.
    """
    record = await _resolve(version, model)
    metrics: dict[str, Any] = dict(record.metrics)

    row = (
        await session.execute(
            sa.select(MLModel).where(MLModel.name == record.name, MLModel.version == record.version)
        )
    ).scalar_one_or_none()
    info = _info_from_row(row) if row is not None else _info_from_record(record)

    headline = record.headline_metrics
    block = (
        MetricsBlock.model_validate(headline)
        if all(value == value for value in headline.values())  # every metric present (no NaN)
        else None
    )

    scatter_raw = metrics.get("predicted_vs_actual")
    scatter = [
        PredictedVsActual.model_validate(entry)
        for entry in (scatter_raw if isinstance(scatter_raw, list) else [])[:_MAX_SCATTER_POINTS]
        if isinstance(entry, dict)
    ]

    residuals_raw = metrics.get("residuals")
    residuals = _residual_histogram(
        [float(value) for value in residuals_raw if isinstance(value, int | float)]
        if isinstance(residuals_raw, list)
        else []
    )

    improvement = metrics.get("mae_improvement_percent")
    return MLMetrics(
        model=info,
        metrics=block,
        predicted_vs_actual=scatter,
        residuals=residuals,
        feature_importance=_feature_importance(metrics),
        mae_improvement_percent=(
            float(improvement) if isinstance(improvement, int | float) else None
        ),
        training_data_note=(
            _TRAINING_DATA_NOTE if info.training_data_origin is DataOrigin.simulated else None
        ),
    )


@router.get(
    "/explain/global",
    response_model=GlobalShapReportOut,
    summary="Global SHAP feature importance",
    description=(
        "Mean |SHAP| per feature over a sample of the training distribution, in kWh/100 km — "
        "what each feature actually moves the prediction by, not how often the trees split on "
        "it.\n\n"
        "Computed once at training time and stored in the metrics file; serving it from there "
        "is what keeps this endpoint a read rather than a minute of SHAP over a sample this "
        "deployment may not even ship."
    ),
)
async def global_explanation(
    model: Annotated[str | None, Query(description="Model name.")] = None,
    version: Annotated[str | None, Query(description="Version; defaults to the active one.")] = (
        None
    ),
) -> GlobalShapReportOut:
    """Return the stored global attribution for one version.

    Raises:
        ModelNotTrainedError: Nothing is trained, or the version has no SHAP block because the
            explainer degraded during training — ``503 configuration_missing``.
    """
    record = await _resolve(version, model)
    shap_block = record.metrics.get("shap")
    if not isinstance(shap_block, dict):
        msg = (
            f"model {record.label} has no SHAP report; retrain it with "
            "`python -m autotwin_ml.cli train` on a build where the shap package is installed"
        )
        raise ModelNotTrainedError(msg, details={"model": record.name, "version": record.version})

    entries_raw = shap_block.get("global_importance")
    entries = [
        GlobalShapEntry.model_validate(entry)
        for entry in (entries_raw if isinstance(entries_raw, list) else [])
        if isinstance(entry, dict)
    ]
    return GlobalShapReportOut(
        model_name=record.name,
        model_version=record.version,
        method=str(shap_block.get("method", "unknown")),
        base_value=float(shap_block.get("base_value", 0.0)),
        sample_rows=int(shap_block.get("sample_rows", 0)),
        background_rows=int(shap_block.get("background_rows", 0)),
        degraded_reason=shap_block.get("degraded_reason"),
        entries=entries,
    )


async def _vehicle_profile(session: DbSession, code: str) -> VehicleProfile:
    """Load a vehicle profile from ``vehicle_models``.

    From the database rather than the built-in constants so that a profile an operator has
    added is usable here too, and so the physical baseline is computed against exactly the
    vehicle the rest of the platform means by that code.

    Raises:
        NotFoundError: The code is not a seeded profile — ``404 not_found``, listing the codes
            that do exist.
    """
    row = (
        await session.execute(sa.select(VehicleModel).where(VehicleModel.code == code))
    ).scalar_one_or_none()
    if row is None:
        known = (
            (await session.execute(sa.select(VehicleModel.code).order_by(VehicleModel.code)))
            .scalars()
            .all()
        )
        msg = f"unknown vehicle profile {code!r}; known profiles: {', '.join(known)}"
        raise NotFoundError(msg, details={"vehicle_code": code, "known": list(known)})
    return VehicleProfile.model_validate(row, from_attributes=True)


def _conditions(payload: PredictRequest) -> SegmentConditions:
    """Build the segment the request describes."""
    return SegmentConditions(
        speed_kmh=float(payload.speed_kmh or 0.0),
        distance_km=payload.distance_km,
        gradient_percent=payload.gradient_percent,
        outside_temperature_c=payload.outside_temperature_c,
        battery_temperature_c=payload.battery_temperature_c,
        acceleration_ms2=payload.acceleration_ms2,
        traffic_severity=payload.traffic_severity,
        precipitation_mm=payload.precipitation_mm,
        wind_speed_ms=payload.wind_speed_ms,
        headwind_ms=payload.headwind_ms,
        road_class=payload.road_class,
        speed_limit_kmh=payload.speed_limit_kmh,
    )


def _contributions(prediction: Prediction) -> list[ShapContribution]:
    """Flatten the explanation onto the wire type, or an empty list when it degraded."""
    explanation = prediction.explanation
    if explanation is None:
        return []
    return [
        ShapContribution(
            feature=item.feature,
            value=item.value,
            contribution=item.contribution,
            direction=item.direction.value,
            label_de=item.label_de,
            label_en=item.label_en,
        )
        for item in explanation.contributions
    ]


@router.post(
    "/predict",
    response_model=PredictResponse,
    summary="Predict consumption for one segment",
    description=(
        "Returns the learned prediction, the **physical baseline for the same segment**, and "
        "the per-feature SHAP contributions that add up to the prediction.\n\n"
        "Ask either with `vehicle_code` plus the segment fields — the baseline is then exact — "
        "or with a complete `features` vector, in which case the baseline is computed against a "
        "reconstructed vehicle and flagged `baseline_is_approximate`.\n\n"
        "Every answer is appended to `ml_predictions`, so a number someone questions later can "
        "be re-explained from the exact vector the model saw."
    ),
)
async def predict(session: DbSession, payload: PredictRequest) -> PredictResponse:
    """Serve one prediction beside its baseline, and record it.

    The estimator call runs in a worker thread: a boosted ensemble plus a SHAP explanation is
    CPU-bound work of the order of milliseconds to tens of milliseconds, which is long enough
    to be worth keeping off the event loop of a service that also streams telemetry.

    Raises:
        ModelNotTrainedError: Nothing is trained — ``503 configuration_missing``.
        NotFoundError: ``vehicle_code`` is not a known profile.
    """
    record = await _resolve(payload.version, None)
    try:
        predictor = await asyncio.to_thread(EnergyPredictor.load, record.version)
    except ModelNotAvailable as exc:
        raise ModelNotTrainedError(exc.message, details=dict(exc.details)) from exc

    profile: VehicleProfile | None = None
    if payload.vehicle_code is not None:
        profile = await _vehicle_profile(session, payload.vehicle_code)

    if payload.features is not None:
        prediction = (
            await asyncio.to_thread(
                predictor.predict_features,
                [payload.features],
                profile=profile,
                explain=payload.explain,
            )
        )[0]
    else:
        if profile is None:
            msg = "`vehicle_code` is required unless a complete `features` vector is supplied"
            raise NotFoundError(msg, details={"vehicle_code": None})
        prediction = await asyncio.to_thread(
            predictor.predict,
            profile,
            _conditions(payload),
            soc_percent=payload.soc_percent,
            explain=payload.explain,
        )

    model_row_id = (
        await session.execute(
            sa.select(MLModel.id).where(
                MLModel.name == prediction.model_name,
                MLModel.version == prediction.model_version,
            )
        )
    ).scalar_one_or_none()
    prediction_id = await record_prediction(
        session,
        prediction,
        ml_model_id=model_row_id,
        context={
            "endpoint": "POST /api/v1/ml/predict",
            "vehicle_code": payload.vehicle_code,
            "distance_km": payload.distance_km,
        },
    )
    await session.commit()

    delta_percent = prediction.delta_percent
    explanation = prediction.explanation
    return PredictResponse(
        prediction_kwh_100km=prediction.prediction_kwh_100km,
        baseline_kwh_100km=prediction.baseline_kwh_100km,
        delta_kwh_100km=prediction.delta_kwh_100km,
        delta_percent=None if delta_percent != delta_percent else delta_percent,
        energy_kwh=prediction.energy_kwh(payload.distance_km),
        baseline_energy_kwh=prediction.baseline_energy_kwh(payload.distance_km),
        model_name=prediction.model_name,
        model_version=prediction.model_version,
        algorithm=prediction.algorithm,
        baseline_is_approximate=prediction.baseline_is_approximate,
        features=dict(prediction.features),
        base_value=explanation.base_value if explanation is not None else None,
        method=explanation.method if explanation is not None else None,
        contributions=_contributions(prediction),
        prediction_id=prediction_id,
        generated_at=utc_now(),
    )
