"""``python -m autotwin_simulator.cli`` — the simulator's command-line contract.

BUILD_SPEC §15 fixes the surface:

.. code-block:: text

    python -m autotwin_simulator.cli run [--vehicles N] [--speed-factor F] [--seed S]
                                        [--duration-s D] [--routes slug,slug] [--sink kafka|db]
    python -m autotwin_simulator.cli generate-training-data [--trips N] [--out PATH]

Both commands accept ``--log-level`` and ``--json-logs``, exit ``0`` on success, ``1`` on a
handled failure and ``2`` on bad arguments. The ``Makefile``, the Compose image and the docs
invoke these exact strings, so the parser is part of the contract.

``argparse`` rather than Click or Typer, per §15. The scenario switches that are *not* in the
spec — ``--weather-mode``, ``--traffic``, ``--tick-seconds``, ``--name``, ``--batches`` — are
additive: every spec invocation works unchanged, and the extra flags exist because
``simulation_runs`` has a ``weather_mode`` and a ``traffic_intensity`` column that would
otherwise only ever hold their defaults.

Structured logs go to **stderr** (``autotwin_core.logging`` configures that), so the one-line
human summary each command prints to **stdout** stays greppable even with ``--json-logs``.
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Final

from autotwin_contracts import utc_now
from autotwin_core.config import LogFormat, Settings, get_settings
from autotwin_core.db.session import dispose_engine, session_scope
from autotwin_core.errors import AutoTwinError
from autotwin_core.logging import configure_logging, get_logger
from autotwin_simulator.engine import (
    SimulationConfig,
    build_environments,
    load_routes_for,
)
from autotwin_simulator.environment import TrafficIntensity, WeatherMode
from autotwin_simulator.runner import SinkFactory, run_standalone
from autotwin_simulator.training_data import (
    DEFAULT_TRAINING_BATCHES,
    DEFAULT_TRAINING_DATA_PATH,
    generate_seasonal_training_data,
)
from autotwin_streaming.config import StreamingConfig
from autotwin_streaming.sinks import TelemetrySink, create_sink

__all__ = ["build_parser", "main"]

_LOGGER = get_logger(__name__)

EXIT_OK: Final[int] = 0
"""The command did what it was asked to do."""

EXIT_FAILURE: Final[int] = 1
"""A handled failure: no corridors seeded, the database refused a write."""

EXIT_USAGE: Final[int] = 2
"""Bad arguments. argparse exits with this on its own; the constant documents the contract."""

TRAINING_WEATHER_DEFAULT: Final[WeatherMode] = WeatherMode.synthetic
"""Weather model ``generate-training-data`` uses unless the operator overrides it.

**Not** ``observed``, and the reason matters. Ingested DWD rows are a *snapshot*: the corridor
is held at whatever the last observation said, so every batch of a training run would see the
same temperature and the model would learn nothing about the winter penalty. The seeded
climatology varies with season, hour and latitude, which is precisely the coverage a training
set needs. A live ``run`` keeps ``observed``, because a demo should show the weather Germany is
actually having."""

TRAINING_TRAFFIC_DEFAULT: Final[TrafficIntensity] = TrafficIntensity.moderate
"""Traffic model ``generate-training-data`` uses unless the operator overrides it.

Same reasoning. ``observed`` marks the few hundred metres around each ingested Autobahn event
and leaves everything else free-flowing, so a training set built that way contains almost no
congested windows and the ``traffic_severity_ordinal`` feature carries no information. The
``moderate`` scenario puts a realistic weekday rush-hour cycle on every corridor."""

DEFAULT_TRAINING_TRIPS: Final[int] = 240
"""Trips generated by ``generate-training-data`` when the operator does not say.

Forty per seasonal batch over the default corridor set is roughly 25 000 windows — enough for a
gradient-boosted model on twenty features to be trained honestly rather than to memorise, and
small enough that generating it takes a couple of minutes on a laptop."""


def build_parser() -> argparse.ArgumentParser:
    """Build the argument parser.

    A function rather than a module-level constant so the tests can build a fresh parser and so
    importing this module has no side effects beyond defining names.
    """
    parser = argparse.ArgumentParser(
        prog="python -m autotwin_simulator.cli",
        description=(
            "AutoTwin DE vehicle simulator: physically-grounded, seeded, and labelled "
            "simulated at every layer (ADR 004)."
        ),
    )
    _add_common_flags(parser)
    subparsers = parser.add_subparsers(dest="command", required=True, metavar="COMMAND")

    run = subparsers.add_parser(
        "run",
        help="drive a simulated fleet along the demo corridors and emit telemetry",
        description=(
            "Start a fleet on the corridors in the routes table, integrate the physical energy "
            "model, and emit TelemetryEvent/TripEvent through the configured sink. Simulated "
            "time starts an hour in the past and fast-forwards until it reaches the present, "
            "after which it tracks real time. Stops cleanly on SIGINT/SIGTERM."
        ),
    )
    _add_common_flags(run)
    _add_scenario_flags(run)
    run.add_argument(
        "--vehicles",
        type=_positive_int,
        metavar="N",
        help="fleet size (default: AUTOTWIN_SIM_DEFAULT_VEHICLES)",
    )
    run.add_argument(
        "--speed-factor",
        type=_positive_float,
        metavar="F",
        help="simulated seconds per wall-clock second (default: AUTOTWIN_SIM_SPEED_FACTOR)",
    )
    run.add_argument(
        "--duration-s",
        type=_positive_float,
        metavar="D",
        help="simulated seconds to run for; omit to run until stopped",
    )
    run.add_argument(
        "--sink",
        choices=("kafka", "db"),
        default=None,
        help=(
            "transport for telemetry. 'kafka' asks for Redpanda and falls back to PostGIS with "
            "a warning if the broker is down; 'db' writes straight to PostGIS. "
            "Default: AUTOTWIN_KAFKA_ENABLED decides."
        ),
    )

    generate = subparsers.add_parser(
        "generate-training-data",
        help="write the ML training set (60 s windows) to Parquet",
        description=(
            "Run the simulator offline across several anchor dates spread over a year, "
            "aggregate the telemetry into 60-second driving windows, and write the feature "
            "table of BUILD_SPEC §10.2. Every row carries data_origin='simulated'."
        ),
    )
    _add_common_flags(generate)
    _add_scenario_flags(
        generate,
        weather_default=TRAINING_WEATHER_DEFAULT.value,
        traffic_default=TRAINING_TRAFFIC_DEFAULT.value,
    )
    generate.add_argument(
        "--trips",
        type=_positive_int,
        default=DEFAULT_TRAINING_TRIPS,
        metavar="N",
        help=f"completed trips to generate across all batches (default: {DEFAULT_TRAINING_TRIPS})",
    )
    generate.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_TRAINING_DATA_PATH,
        metavar="PATH",
        help=f"Parquet destination (default: {DEFAULT_TRAINING_DATA_PATH})",
    )
    generate.add_argument(
        "--batches",
        type=_positive_int,
        default=DEFAULT_TRAINING_BATCHES,
        metavar="N",
        help=(
            "seasonal batches the trip budget is split across; more batches means a wider "
            f"temperature range in the training set (default: {DEFAULT_TRAINING_BATCHES})"
        ),
    )
    generate.add_argument(
        "--vehicles",
        type=_positive_int,
        metavar="N",
        help="fleet size per batch (default: AUTOTWIN_SIM_DEFAULT_VEHICLES)",
    )

    return parser


def _add_common_flags(parser: argparse.ArgumentParser) -> None:
    """Attach ``--log-level`` and ``--json-logs`` (BUILD_SPEC §15).

    Added to the top-level parser *and* to each subparser so that both ``cli --json-logs run``
    and ``cli run --json-logs`` work. Operators reach for the second spelling; shell history
    produces the first.
    """
    parser.add_argument(
        "--log-level",
        default=None,
        metavar="LEVEL",
        help="log level name, e.g. DEBUG or INFO (default: AUTOTWIN_LOG_LEVEL)",
    )
    parser.add_argument(
        "--json-logs",
        action="store_true",
        default=None,
        help="render logs as one JSON object per line instead of console output",
    )


def _add_scenario_flags(
    parser: argparse.ArgumentParser,
    *,
    weather_default: str | None = None,
    traffic_default: str | None = None,
) -> None:
    """Attach the flags both subcommands share: corridors, seed, weather and traffic.

    The two defaults differ by subcommand. ``run`` defers to the data (``observed``), because a
    live demo should show the weather Germany is actually having. ``generate-training-data``
    does not: see :data:`TRAINING_WEATHER_DEFAULT`.
    """
    parser.add_argument(
        "--seed",
        type=int,
        metavar="S",
        help="master RNG seed; the same seed reproduces the run (default: AUTOTWIN_SIM_SEED)",
    )
    parser.add_argument(
        "--routes",
        default=None,
        metavar="SLUG,SLUG",
        help="comma-separated route slugs to drive (default: every corridor, demo ones first)",
    )
    parser.add_argument(
        "--tick-seconds",
        type=_positive_float,
        metavar="S",
        help="wall-clock seconds between ticks (default: AUTOTWIN_SIM_TICK_SECONDS)",
    )
    parser.add_argument(
        "--weather-mode",
        choices=tuple(mode.value for mode in WeatherMode),
        default=weather_default,
        help=(
            "where ambient weather comes from. 'observed' prefers ingested DWD rows; "
            "cold/mild/hot pin the whole fleet to -10/+20/+35 °C "
            f"(default: {weather_default or WeatherMode.observed.value})"
        ),
    )
    parser.add_argument(
        "--traffic",
        choices=tuple(intensity.value for intensity in TrafficIntensity),
        default=traffic_default,
        dest="traffic_intensity",
        help=(
            "congestion model. 'observed' uses ingested Autobahn events and falls back to a "
            "seeded rush-hour model on corridors without any "
            f"(default: {traffic_default or TrafficIntensity.observed.value})"
        ),
    )
    parser.add_argument(
        "--name",
        default=None,
        metavar="NAME",
        help="label written to simulation_runs.name",
    )


def _positive_int(raw: str) -> int:
    """Parse a strictly positive integer, or raise the error argparse turns into exit code 2."""
    try:
        value = int(raw)
    except ValueError as exc:
        msg = f"{raw!r} is not an integer"
        raise argparse.ArgumentTypeError(msg) from exc
    if value <= 0:
        msg = f"must be greater than zero, got {value}"
        raise argparse.ArgumentTypeError(msg)
    return value


def _positive_float(raw: str) -> float:
    """Parse a strictly positive float, or raise the error argparse turns into exit code 2."""
    try:
        value = float(raw)
    except ValueError as exc:
        msg = f"{raw!r} is not a number"
        raise argparse.ArgumentTypeError(msg) from exc
    if value <= 0.0:
        msg = f"must be greater than zero, got {value}"
        raise argparse.ArgumentTypeError(msg)
    return value


def _configure(namespace: argparse.Namespace) -> Settings:
    """Apply the logging flags on top of the configured settings and return them.

    ``Settings`` is not mutated: a copy carries the log overrides, so the process-wide cached
    settings keep describing the environment and only the rendering follows the flag.
    """
    settings = get_settings()
    overrides: dict[str, object] = {}
    if namespace.log_level:
        overrides["log_level"] = str(namespace.log_level).upper()
    if namespace.json_logs:
        overrides["log_format"] = LogFormat.json
    resolved = settings.model_copy(update=overrides) if overrides else settings
    configure_logging(resolved)
    return resolved


def _build_config(
    namespace: argparse.Namespace,
    settings: Settings,
    **extra: object,
) -> SimulationConfig:
    """Translate the parsed flags into a :class:`SimulationConfig`.

    ``None`` means "the operator did not say", and
    :meth:`SimulationConfig.from_settings` then falls back to ``AUTOTWIN_SIM_*``. That is why
    every numeric flag defaults to ``None`` rather than to a literal — a literal here would
    silently override the environment.
    """
    slugs = _parse_slugs(namespace.routes)
    overrides: dict[str, object] = {
        "vehicle_count": getattr(namespace, "vehicles", None),
        "speed_factor": getattr(namespace, "speed_factor", None),
        "tick_seconds": namespace.tick_seconds,
        "seed": namespace.seed,
        "duration_s": getattr(namespace, "duration_s", None),
        "route_slugs": slugs or None,
        "name": namespace.name,
        "weather_mode": WeatherMode(namespace.weather_mode) if namespace.weather_mode else None,
        "traffic_intensity": (
            TrafficIntensity(namespace.traffic_intensity) if namespace.traffic_intensity else None
        ),
        **extra,
    }
    return SimulationConfig.from_settings(settings, **overrides)


def _parse_slugs(raw: str | None) -> tuple[str, ...]:
    """Split ``--routes a,b,c`` into slugs, tolerating spaces and trailing commas."""
    if not raw:
        return ()
    return tuple(part.strip() for part in raw.split(",") if part.strip())


def _sink_factory(choice: str | None, settings: Settings) -> SinkFactory | None:
    """Turn ``--sink`` into a factory, or ``None`` to let the settings decide.

    ``kafka`` still goes through :func:`~autotwin_streaming.sinks.create_sink`, which probes the
    broker and falls back to PostGIS with a warning. Asking for Kafka and getting a hard failure
    because Redpanda is not up would contradict BUILD_SPEC §0.3 — degrade, never crash — and the
    degradation is visible in the sink's ``degraded_reason``.
    """
    if choice is None:
        return None
    enabled = choice == "kafka"

    async def factory() -> TelemetrySink:
        config = StreamingConfig.from_settings(settings).with_overrides(enabled=enabled)
        return await create_sink(settings, config=config)

    return factory


async def _run_simulation(namespace: argparse.Namespace, settings: Settings) -> int:
    """Run a fleet until the duration elapses or a signal arrives, then summarise."""
    config = _build_config(namespace, settings)
    stats = await run_standalone(
        config,
        settings=settings,
        sink_factory=_sink_factory(namespace.sink, settings),
    )
    # The one deliberate print: BUILD_SPEC §15 asks every command to end with a human-readable
    # summary on stdout, while the structured log goes to stderr.
    print(
        f"simulated {stats.simulated_seconds / 3600.0:.2f} h with {config.vehicle_count} "
        f"vehicle(s): {stats.events_emitted} telemetry event(s), "
        f"{stats.trip_events_emitted} trip event(s), {stats.ticks} tick(s), "
        f"{stats.events_per_second:.1f} events/s, {stats.errors} error(s)"
    )
    return EXIT_FAILURE if stats.errors and stats.events_emitted == 0 else EXIT_OK


async def _run_generate_training_data(namespace: argparse.Namespace, settings: Settings) -> int:
    """Generate the ML training set offline and write it to Parquet."""
    config = _build_config(namespace, settings, realtime=False, duration_s=None)
    async with session_scope() as session:
        routes = await load_routes_for(session, config)
        environments = await build_environments(config, routes, session=session, now=utc_now())
    result = await generate_seasonal_training_data(
        config,
        environments,
        trips=namespace.trips,
        batches=namespace.batches,
        out=namespace.out,
    )
    await dispose_engine()
    print(result.summary())
    return EXIT_OK


async def _dispatch(namespace: argparse.Namespace, settings: Settings) -> int:
    """Run the selected subcommand, mapping a handled failure onto exit code 1."""
    handlers = {
        "run": _run_simulation,
        "generate-training-data": _run_generate_training_data,
    }
    handler = handlers[namespace.command]
    try:
        return await handler(namespace, settings)
    except AutoTwinError as exc:
        # Everything AutoTwin raises deliberately is a handled failure: report it and exit 1.
        # Anything else is a bug and keeps its traceback.
        _LOGGER.error(
            "cli.command_failed",
            command=namespace.command,
            code=exc.code,
            message=exc.message,
            **exc.details,
        )
        print(f"error: {exc.message}", file=sys.stderr)
        return EXIT_FAILURE


def main(argv: Sequence[str] | None = None) -> int:
    """Entry point: parse, configure logging, dispatch, and return the process exit code."""
    parser = build_parser()
    namespace = parser.parse_args(argv)
    settings = _configure(namespace)
    try:
        return asyncio.run(_dispatch(namespace, settings))
    except KeyboardInterrupt:
        # Reachable when the signal arrives before the runner has installed its own handler.
        _LOGGER.info("cli.interrupted", command=namespace.command)
        return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
