"""initial schema

Revision ID: 0001
Revises:
Created: 2026-09-14 14:09:28.651919+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# --------------------------------------------------------------------------------------
# Enum types
#
# Several enums are used by more than one table. Alembic's autogenerated `sa.Enum(...)`
# emits a CREATE TYPE for *every* table that references it, so the second table fails with
# "type already exists". The types are therefore created once, explicitly, at the top of
# upgrade(), and every column reference below is rendered with create_type=False.
#
# Values are the *member values* of the enums in `autotwin_contracts.enums` (BUILD_SPEC §2).
# They are a wire format shared by the database, the API and the TypeScript frontend:
# changing one here without changing it there breaks all three at once.
# --------------------------------------------------------------------------------------

ENUM_VALUES: dict[str, tuple[str, ...]] = {
    "bundesland": (
        "BW",
        "BY",
        "BE",
        "BB",
        "HB",
        "HH",
        "HE",
        "MV",
        "NI",
        "NW",
        "RP",
        "SL",
        "SN",
        "ST",
        "SH",
        "TH",
    ),
    "charging_category": (
        "normal",
        "fast",
        "ultra_fast",
    ),
    "connector_type": (
        "type2",
        "ccs",
        "chademo",
        "schuko",
        "tesla",
        "cee",
        "other",
        "unknown",
    ),
    "current_type": (
        "ac",
        "dc",
        "unknown",
    ),
    "data_origin": (
        "official",
        "simulated",
        "derived",
    ),
    "energy_intensity": (
        "low",
        "medium",
        "high",
        "critical",
    ),
    "ingestion_outcome": (
        "success",
        "partial",
        "failed",
    ),
    "provider_mode": (
        "live",
        "cache",
        "fixture",
    ),
    "road_class": (
        "motorway",
        "trunk",
        "primary",
        "secondary",
        "tertiary",
        "residential",
        "service",
        "unknown",
    ),
    "simulation_state": (
        "pending",
        "running",
        "paused",
        "stopping",
        "stopped",
        "completed",
        "failed",
    ),
    "source_system": (
        "bundesnetzagentur",
        "dwd",
        "autobahn",
        "mobilithek",
        "osm",
        "osrm",
        "simulator",
        "derived",
    ),
    "traffic_event_type": (
        "roadworks",
        "closure",
        "incident",
        "warning",
        "congestion",
        "other",
    ),
    "traffic_severity": (
        "low",
        "moderate",
        "high",
        "severe",
    ),
    "vehicle_class": (
        "compact",
        "sedan",
        "performance",
        "suv",
        "van",
    ),
    "vehicle_state": (
        "idle",
        "driving",
        "charging",
        "stopped",
        "completed",
    ),
    "weather_condition": (
        "clear",
        "clouds",
        "rain",
        "snow",
        "fog",
        "storm",
        "unknown",
    ),
}


def _enum(name: str) -> postgresql.ENUM:
    """Reference an existing enum type without trying to create it."""
    return postgresql.ENUM(*ENUM_VALUES[name], name=name, create_type=False)


def _create_enum_types() -> None:
    bind = op.get_bind()
    for name, values in ENUM_VALUES.items():
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)


def _drop_enum_types() -> None:
    bind = op.get_bind()
    for name, values in ENUM_VALUES.items():
        postgresql.ENUM(*values, name=name).drop(bind, checkfirst=True)


def upgrade() -> None:
    # PostGIS must exist before any geography/geometry column is declared. The compose init
    # script also creates it, but a migration has to stand on its own: `alembic upgrade head`
    # against a bare PostgreSQL with the PostGIS libraries installed must work.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    _create_enum_types()

    op.create_table(
        "data_ingestion_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "source",
            _enum("source_system"),
            nullable=False,
        ),
        sa.Column("pipeline", sa.Text(), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "status",
            _enum("ingestion_outcome"),
            nullable=False,
        ),
        sa.Column(
            "provider_mode",
            _enum("provider_mode"),
            nullable=False,
        ),
        sa.Column("rows_received", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_accepted", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_rejected", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_duplicate", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("bytes_downloaded", sa.BigInteger(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_file_sha256", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("quality_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_ingestion_runs")),
    )
    op.create_index(
        "ix_data_ingestion_runs_source_started_at",
        "data_ingestion_runs",
        ["source", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "ml_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("algorithm", sa.Text(), nullable=False),
        sa.Column("trained_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("training_rows", sa.Integer(), nullable=False),
        sa.Column("feature_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_path", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "training_data_origin",
            _enum("data_origin"),
            server_default="simulated",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ml_models")),
        sa.UniqueConstraint("name", "version", name=op.f("uq_ml_models_name_version")),
    )
    op.create_table(
        "simulation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "state",
            _enum("simulation_state"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("vehicle_count", sa.Integer(), nullable=False),
        sa.Column("speed_factor", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("weather_mode", sa.Text(), nullable=False),
        sa.Column("traffic_intensity", sa.Text(), nullable=False),
        sa.Column("vehicle_mix", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("route_slugs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("events_emitted", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("errors", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_runs")),
    )
    op.create_table(
        "telemetry",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("vehicle_id", sa.Text(), nullable=False),
        sa.Column("trip_id", sa.Text(), nullable=True),
        sa.Column("route_id", sa.UUID(), nullable=True),
        sa.Column("recorded_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT", srid=4326, spatial_index=False, nullable=False
            ),
            nullable=False,
        ),
        sa.Column("speed_kmh", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("acceleration_ms2", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("heading_deg", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("battery_soc_percent", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("battery_temperature_c", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("outside_temperature_c", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("instantaneous_power_kw", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("energy_consumption_kwh_100km", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("cumulative_energy_kwh", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("estimated_range_km", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column(
            "road_class",
            _enum("road_class"),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("speed_limit_kmh", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("odometer_m", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column(
            "state",
            _enum("vehicle_state"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            _enum("data_origin"),
            server_default="simulated",
            nullable=False,
        ),
        sa.Column(
            "ingested_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry")),
    )
    op.create_index(
        "ix_telemetry_location", "telemetry", ["location"], unique=False, postgresql_using="gist"
    )
    op.create_index(
        "ix_telemetry_recorded_at",
        "telemetry",
        [sa.literal_column("recorded_at DESC")],
        unique=False,
    )
    op.create_index("ix_telemetry_trip_id", "telemetry", ["trip_id"], unique=False)
    op.create_index(
        "ix_telemetry_vehicle_id_recorded_at",
        "telemetry",
        ["vehicle_id", sa.literal_column("recorded_at DESC")],
        unique=False,
    )
    op.create_table(
        "vehicle_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "vehicle_class",
            _enum("vehicle_class"),
            nullable=False,
        ),
        sa.Column("battery_capacity_kwh", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("usable_capacity_kwh", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("nominal_consumption_kwh_100km", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("max_dc_power_kw", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("max_ac_power_kw", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("mass_kg", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("drag_coefficient", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("frontal_area_m2", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("rolling_resistance", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("is_generic", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_models")),
        sa.UniqueConstraint("code", name=op.f("uq_vehicle_models_code")),
    )
    op.create_table(
        "weather_stations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dwd_station_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT", srid=4326, spatial_index=False, nullable=False
            ),
            nullable=False,
        ),
        sa.Column("elevation_m", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column(
            "bundesland",
            _enum("bundesland"),
            nullable=True,
        ),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_stations")),
        sa.UniqueConstraint("dwd_station_id", name=op.f("uq_weather_stations_dwd_station_id")),
    )
    op.create_index(
        "ix_weather_stations_location",
        "weather_stations",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "charging_stations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("operator", sa.Text(), nullable=True),
        sa.Column("street", sa.Text(), nullable=True),
        sa.Column("house_number", sa.Text(), nullable=True),
        sa.Column("postal_code", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column(
            "bundesland",
            _enum("bundesland"),
            nullable=True,
        ),
        sa.Column("country", sa.Text(), server_default="DE", nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT", srid=4326, spatial_index=False, nullable=False
            ),
            nullable=False,
        ),
        sa.Column("commissioned_on", sa.Date(), nullable=True),
        sa.Column(
            "charging_points_count", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("max_power_kw", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("total_power_kw", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column(
            "charging_category",
            _enum("charging_category"),
            nullable=False,
        ),
        sa.Column("is_fast_charger", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "source",
            _enum("source_system"),
            nullable=False,
        ),
        sa.Column("source_identifier", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "data_origin",
            _enum("data_origin"),
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["data_ingestion_runs.id"],
            name=op.f("fk_charging_stations_ingestion_run_id_data_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charging_stations")),
        sa.UniqueConstraint("external_id", name=op.f("uq_charging_stations_external_id")),
    )
    op.create_index(
        "ix_charging_stations_bundesland", "charging_stations", ["bundesland"], unique=False
    )
    op.create_index(
        "ix_charging_stations_charging_category",
        "charging_stations",
        ["charging_category"],
        unique=False,
    )
    op.create_index(
        "ix_charging_stations_location",
        "charging_stations",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "ix_charging_stations_max_power_kw",
        "charging_stations",
        [sa.literal_column("max_power_kw DESC")],
        unique=False,
    )
    op.create_index(
        "ix_charging_stations_operator", "charging_stations", ["operator"], unique=False
    )
    op.create_table(
        "ml_predictions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ml_model_id", sa.UUID(), nullable=True),
        sa.Column("route_id", sa.UUID(), nullable=True),
        sa.Column("trip_id", sa.Text(), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prediction_kwh_100km", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("baseline_kwh_100km", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("shap_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ml_model_id"],
            ["ml_models.id"],
            name=op.f("fk_ml_predictions_ml_model_id_ml_models"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ml_predictions")),
    )
    op.create_table(
        "routes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("origin_name", sa.Text(), nullable=False),
        sa.Column("destination_name", sa.Text(), nullable=False),
        sa.Column(
            "origin",
            geoalchemy2.types.Geography(
                geometry_type="POINT", srid=4326, spatial_index=False, nullable=False
            ),
            nullable=False,
        ),
        sa.Column(
            "destination",
            geoalchemy2.types.Geography(
                geometry_type="POINT", srid=4326, spatial_index=False, nullable=False
            ),
            nullable=False,
        ),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING", srid=4326, spatial_index=False, nullable=False
            ),
            nullable=False,
        ),
        sa.Column("distance_m", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("duration_s", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("routing_profile", sa.Text(), server_default="driving", nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "source",
            _enum("source_system"),
            nullable=False,
        ),
        sa.Column("source_identifier", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "data_origin",
            _enum("data_origin"),
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["data_ingestion_runs.id"],
            name=op.f("fk_routes_ingestion_run_id_data_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routes")),
        sa.UniqueConstraint("slug", name=op.f("uq_routes_slug")),
    )
    op.create_index(
        "ix_routes_geometry", "routes", ["geometry"], unique=False, postgresql_using="gist"
    )
    op.create_table(
        "traffic_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column(
            "event_type",
            _enum("traffic_event_type"),
            nullable=False,
        ),
        sa.Column(
            "severity",
            _enum("traffic_severity"),
            server_default="moderate",
            nullable=False,
        ),
        sa.Column("road_name", sa.Text(), nullable=True),
        sa.Column("direction", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT", srid=4326, spatial_index=False, nullable=False
            ),
            nullable=False,
        ),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING", srid=4326, spatial_index=False, nullable=False
            ),
            nullable=False,
        ),
        sa.Column("starts_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("ends_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("is_blocked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("delay_minutes", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "source",
            _enum("source_system"),
            nullable=False,
        ),
        sa.Column("source_identifier", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "data_origin",
            _enum("data_origin"),
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["data_ingestion_runs.id"],
            name=op.f("fk_traffic_events_ingestion_run_id_data_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_traffic_events")),
        sa.UniqueConstraint("external_id", name=op.f("uq_traffic_events_external_id")),
    )
    op.create_index("ix_traffic_events_event_type", "traffic_events", ["event_type"], unique=False)
    op.create_index(
        "ix_traffic_events_location",
        "traffic_events",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index("ix_traffic_events_road_name", "traffic_events", ["road_name"], unique=False)
    op.create_index(
        "ix_traffic_events_starts_at",
        "traffic_events",
        [sa.literal_column("starts_at DESC")],
        unique=False,
    )
    op.create_table(
        "vehicles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.Text(), nullable=False),
        sa.Column("vehicle_model_id", sa.UUID(), nullable=False),
        sa.Column("simulation_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "state",
            _enum("vehicle_state"),
            server_default="idle",
            nullable=False,
        ),
        sa.Column(
            "source",
            _enum("source_system"),
            nullable=False,
        ),
        sa.Column("source_identifier", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "data_origin",
            _enum("data_origin"),
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["data_ingestion_runs.id"],
            name=op.f("fk_vehicles_ingestion_run_id_data_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["simulation_run_id"],
            ["simulation_runs.id"],
            name=op.f("fk_vehicles_simulation_run_id_simulation_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_model_id"],
            ["vehicle_models.id"],
            name=op.f("fk_vehicles_vehicle_model_id_vehicle_models"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint("vehicle_id", name=op.f("uq_vehicles_vehicle_id")),
    )
    op.create_table(
        "weather_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("weather_station_id", sa.UUID(), nullable=True),
        sa.Column("observed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT", srid=4326, spatial_index=False, nullable=False
            ),
            nullable=False,
        ),
        sa.Column("temperature_c", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("precipitation_mm", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("wind_speed_ms", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("wind_gust_ms", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("humidity_percent", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("pressure_hpa", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column(
            "condition",
            _enum("weather_condition"),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "source",
            _enum("source_system"),
            nullable=False,
        ),
        sa.Column("source_identifier", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "data_origin",
            _enum("data_origin"),
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["data_ingestion_runs.id"],
            name=op.f("fk_weather_observations_ingestion_run_id_data_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["weather_station_id"],
            ["weather_stations.id"],
            name=op.f("fk_weather_observations_weather_station_id_weather_stations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_observations")),
        sa.UniqueConstraint(
            "weather_station_id",
            "observed_at",
            name=op.f("uq_weather_observations_weather_station_id_observed_at"),
        ),
    )
    op.create_index(
        "ix_weather_observations_location",
        "weather_observations",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "ix_weather_observations_observed_at",
        "weather_observations",
        [sa.literal_column("observed_at DESC")],
        unique=False,
    )
    op.create_table(
        "charging_points",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "connector_type",
            _enum("connector_type"),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "current_type",
            _enum("current_type"),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("power_kw", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("public_key", sa.Text(), nullable=True),
        sa.Column(
            "source",
            _enum("source_system"),
            nullable=False,
        ),
        sa.Column("source_identifier", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "data_origin",
            _enum("data_origin"),
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["data_ingestion_runs.id"],
            name=op.f("fk_charging_points_ingestion_run_id_data_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["charging_stations.id"],
            name=op.f("fk_charging_points_station_id_charging_stations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charging_points")),
    )
    op.create_index(
        "ix_charging_points_station_id", "charging_points", ["station_id"], unique=False
    )
    op.create_table(
        "route_segments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING", srid=4326, spatial_index=False, nullable=False
            ),
            nullable=False,
        ),
        sa.Column("start_offset_m", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("distance_m", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column(
            "road_class",
            _enum("road_class"),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("speed_limit_kmh", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("assumed_speed_kmh", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("elevation_gain_m", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("temperature_c", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column(
            "traffic_severity",
            _enum("traffic_severity"),
            nullable=True,
        ),
        sa.Column("predicted_kwh_per_100km", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("predicted_kwh", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column(
            "energy_intensity",
            _enum("energy_intensity"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
            name=op.f("fk_route_segments_route_id_routes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_segments")),
        sa.UniqueConstraint("route_id", "ordinal", name=op.f("uq_route_segments_route_id_ordinal")),
    )
    op.create_index(
        "ix_route_segments_geometry",
        "route_segments",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "trips",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("ended_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("start_soc_percent", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("end_soc_percent", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("distance_m", sa.DOUBLE_PRECISION(), server_default=sa.text("0"), nullable=False),
        sa.Column("energy_kwh", sa.DOUBLE_PRECISION(), server_default=sa.text("0"), nullable=False),
        sa.Column("avg_consumption_kwh_100km", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column(
            "state",
            _enum("vehicle_state"),
            server_default="driving",
            nullable=False,
        ),
        sa.Column(
            "source",
            _enum("source_system"),
            nullable=False,
        ),
        sa.Column("source_identifier", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "data_origin",
            _enum("data_origin"),
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["data_ingestion_runs.id"],
            name=op.f("fk_trips_ingestion_run_id_data_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["route_id"], ["routes.id"], name=op.f("fk_trips_route_id_routes"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_trips_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
        sa.UniqueConstraint("trip_id", name=op.f("uq_trips_trip_id")),
    )
    op.create_index(
        "ix_trips_vehicle_id_started_at",
        "trips",
        ["vehicle_id", sa.literal_column("started_at DESC")],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_trips_vehicle_id_started_at", table_name="trips")
    op.drop_table("trips")
    op.drop_index(
        "ix_route_segments_geometry", table_name="route_segments", postgresql_using="gist"
    )
    op.drop_table("route_segments")
    op.drop_index("ix_charging_points_station_id", table_name="charging_points")
    op.drop_table("charging_points")
    op.drop_index("ix_weather_observations_observed_at", table_name="weather_observations")
    op.drop_index(
        "ix_weather_observations_location",
        table_name="weather_observations",
        postgresql_using="gist",
    )
    op.drop_table("weather_observations")
    op.drop_table("vehicles")
    op.drop_index("ix_traffic_events_starts_at", table_name="traffic_events")
    op.drop_index("ix_traffic_events_road_name", table_name="traffic_events")
    op.drop_index(
        "ix_traffic_events_location", table_name="traffic_events", postgresql_using="gist"
    )
    op.drop_index("ix_traffic_events_event_type", table_name="traffic_events")
    op.drop_table("traffic_events")
    op.drop_index("ix_routes_geometry", table_name="routes", postgresql_using="gist")
    op.drop_table("routes")
    op.drop_table("ml_predictions")
    op.drop_index("ix_charging_stations_operator", table_name="charging_stations")
    op.drop_index("ix_charging_stations_max_power_kw", table_name="charging_stations")
    op.drop_index(
        "ix_charging_stations_location", table_name="charging_stations", postgresql_using="gist"
    )
    op.drop_index("ix_charging_stations_charging_category", table_name="charging_stations")
    op.drop_index("ix_charging_stations_bundesland", table_name="charging_stations")
    op.drop_table("charging_stations")
    op.drop_index(
        "ix_weather_stations_location", table_name="weather_stations", postgresql_using="gist"
    )
    op.drop_table("weather_stations")
    op.drop_table("vehicle_models")
    op.drop_index("ix_telemetry_vehicle_id_recorded_at", table_name="telemetry")
    op.drop_index("ix_telemetry_trip_id", table_name="telemetry")
    op.drop_index("ix_telemetry_recorded_at", table_name="telemetry")
    op.drop_index("ix_telemetry_location", table_name="telemetry", postgresql_using="gist")
    op.drop_table("telemetry")
    op.drop_table("simulation_runs")
    op.drop_table("ml_models")
    op.drop_index("ix_data_ingestion_runs_source_started_at", table_name="data_ingestion_runs")
    op.drop_table("data_ingestion_runs")
    _drop_enum_types()
