"""AutoTwin DE shared contracts — enums, records, events and API envelopes.

This package is the vocabulary every other AutoTwin module is written against
(``docs/BUILD_SPEC.md`` §1). It depends on Pydantic and the standard library only: no
SQLAlchemy, no FastAPI, no sibling package. That constraint is what makes the dependency
graph acyclic and lets a provider adapter or an ML feature builder be unit-tested without a
database or a web framework.

Everything worth importing is re-exported here, so downstream code writes
``from autotwin_contracts import Coordinate, TelemetryEvent`` rather than reaching into
submodules. Submodule imports remain valid and are preferred inside this package itself.
"""

from __future__ import annotations

from autotwin_contracts.api import (
    DATA_MODE_HEADER,
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    REQUEST_ID_HEADER,
    DataModeInfo,
    ErrorCode,
    ErrorDetail,
    ErrorResponse,
    HealthResponse,
    Page,
    PaginationParams,
    ReadinessChecks,
    ReadyResponse,
)
from autotwin_contracts.enums import (
    Bundesland,
    ChargingCategory,
    ConnectorType,
    CurrentType,
    DataOrigin,
    EnergyIntensity,
    IngestionOutcome,
    IngestionStatus,
    ProviderMode,
    RoadClass,
    SimulationState,
    SourceSystem,
    TrafficEventType,
    TrafficSeverity,
    VehicleClass,
    VehicleState,
    WeatherCondition,
)
from autotwin_contracts.events import (
    ALL_TOPICS,
    EVENT_TYPE_CHARGING,
    EVENT_TYPE_TELEMETRY,
    EVENT_TYPE_TRAFFIC,
    EVENT_TYPE_TRIP,
    SCHEMA_VERSION,
    TOPIC_CHARGING_EVENTS,
    TOPIC_TELEMETRY,
    TOPIC_TRAFFIC_EVENTS,
    TOPIC_TRIP_EVENTS,
    ChargingEvent,
    ChargingEventEnvelope,
    ChargingEventType,
    EventEnvelope,
    TelemetryEnvelope,
    TelemetryEvent,
    TrafficEventEnvelope,
    TrafficEventMessage,
    TripEnvelope,
    TripEvent,
    TripEventType,
)
from autotwin_contracts.geo import (
    EARTH_RADIUS_KM,
    GERMANY_BBOX,
    BoundingBox,
    Coordinate,
    GeoJSONFeature,
    GeoJSONFeatureCollection,
    GeoJSONGeometry,
    GeoJSONLineString,
    GeoJSONPoint,
    Position,
    haversine_km,
)
from autotwin_contracts.records import (
    FAST_CHARGER_THRESHOLD_KW,
    ChargingPointRecord,
    ChargingStationRecord,
    Place,
    ProvenanceInfo,
    RouteResult,
    RouteStepRecord,
    TrafficEventRecord,
    WeatherRecord,
    WeatherStationRecord,
)
from autotwin_contracts.temporal import UtcDatetime, ensure_utc, utc_now
from autotwin_contracts.vehicles import (
    GENERIC_VEHICLE_PROFILES,
    VEHICLE_PROFILES_BY_CODE,
    VehicleProfile,
    get_vehicle_profile,
)

__version__ = "0.1.0"

__all__ = [
    "ALL_TOPICS",
    "DATA_MODE_HEADER",
    "DEFAULT_PAGE_SIZE",
    "EARTH_RADIUS_KM",
    "EVENT_TYPE_CHARGING",
    "EVENT_TYPE_TELEMETRY",
    "EVENT_TYPE_TRAFFIC",
    "EVENT_TYPE_TRIP",
    "FAST_CHARGER_THRESHOLD_KW",
    "GENERIC_VEHICLE_PROFILES",
    "GERMANY_BBOX",
    "MAX_PAGE_SIZE",
    "REQUEST_ID_HEADER",
    "SCHEMA_VERSION",
    "TOPIC_CHARGING_EVENTS",
    "TOPIC_TELEMETRY",
    "TOPIC_TRAFFIC_EVENTS",
    "TOPIC_TRIP_EVENTS",
    "VEHICLE_PROFILES_BY_CODE",
    "BoundingBox",
    "Bundesland",
    "ChargingCategory",
    "ChargingEvent",
    "ChargingEventEnvelope",
    "ChargingEventType",
    "ChargingPointRecord",
    "ChargingStationRecord",
    "ConnectorType",
    "Coordinate",
    "CurrentType",
    "DataModeInfo",
    "DataOrigin",
    "EnergyIntensity",
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "EventEnvelope",
    "GeoJSONFeature",
    "GeoJSONFeatureCollection",
    "GeoJSONGeometry",
    "GeoJSONLineString",
    "GeoJSONPoint",
    "HealthResponse",
    "IngestionOutcome",
    "IngestionStatus",
    "Page",
    "PaginationParams",
    "Place",
    "Position",
    "ProvenanceInfo",
    "ProviderMode",
    "ReadinessChecks",
    "ReadyResponse",
    "RoadClass",
    "RouteResult",
    "RouteStepRecord",
    "SimulationState",
    "SourceSystem",
    "TelemetryEnvelope",
    "TelemetryEvent",
    "TrafficEventEnvelope",
    "TrafficEventMessage",
    "TrafficEventRecord",
    "TrafficEventType",
    "TrafficSeverity",
    "TripEnvelope",
    "TripEvent",
    "TripEventType",
    "UtcDatetime",
    "VehicleClass",
    "VehicleProfile",
    "VehicleState",
    "WeatherCondition",
    "WeatherRecord",
    "WeatherStationRecord",
    "__version__",
    "ensure_utc",
    "get_vehicle_profile",
    "haversine_km",
    "utc_now",
]
