"""Fleet payloads: vehicles, their live telemetry and their trips.

Everything in this module describes **simulated** data (BUILD_SPEC §0.2). The vehicles are
generated by :mod:`autotwin_simulator`, the telemetry is a physics model's output, and every
row carries ``data_origin = simulated`` in the database. The API never dresses it up as
measurement: :class:`VehicleDetail` and :class:`TripDetail` both carry the provenance block, and
the frontend renders the *SIMULIERT* badge from it.

The trip models live here rather than in a module of their own because a trip is a vehicle's
history — the two endpoints read the same three tables and share :class:`TelemetryPoint` — and
splitting them would only buy an import cycle between the two schema modules.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import Field

from autotwin_api.schemas.common import ApiModel, ProvenanceOut
from autotwin_contracts import RoadClass, VehicleClass, VehicleState

__all__ = [
    "TelemetryPoint",
    "TripDetail",
    "TripSeriesPoint",
    "TripSummary",
    "VehicleDetail",
    "VehicleLive",
    "VehicleSummary",
]


class VehicleSummary(ApiModel):
    """One vehicle of the simulated fleet, as the list endpoint returns it."""

    id: UUID = Field(..., description="Surrogate key of the `vehicles` row.")
    vehicle_id: str = Field(
        ...,
        description="Stable fleet identifier, e.g. `ATW-0042`. The same car across runs.",
        examples=["ATW-0042"],
    )
    model_code: str = Field(
        ...,
        description="Vehicle profile code (BUILD_SPEC §9), e.g. `compact_ev`.",
    )
    model_display_name: str = Field(..., description="Human label of the profile.")
    vehicle_class: VehicleClass = Field(
        ...,
        description="compact, sedan, performance, suv or van.",
    )
    state: VehicleState = Field(
        ...,
        description="idle, driving, charging, stopped or completed.",
    )
    simulation_run_id: UUID | None = Field(
        default=None,
        description="The run that most recently owned this vehicle.",
    )
    last_seen_at: datetime | None = Field(
        default=None,
        description="Timestamp of its newest telemetry sample (UTC); null if it never reported.",
    )
    battery_soc_percent: float | None = Field(
        default=None,
        description="State of charge at that sample, in percent.",
    )
    odometer_m: float | None = Field(
        default=None,
        description="Distance driven since the fleet was created, in metres.",
    )


class VehicleLive(ApiModel):
    """The newest telemetry sample of one vehicle — a marker on the live map.

    This is the SSE payload as well as the body of ``GET /api/v1/vehicles/live``; both produce
    exactly this shape so the frontend's merge of stream deltas into the initial snapshot is a
    plain ``Map.set`` and never a reconciliation.
    """

    vehicle_id: str = Field(..., description="Fleet identifier, e.g. `ATW-0042`.")
    trip_id: str | None = Field(default=None, description="Trip the sample belongs to.")
    route_id: UUID | None = Field(default=None, description="Corridor being driven.")
    model_code: str = Field(..., description="Vehicle profile code, e.g. `sedan_ev`.")
    recorded_at: datetime = Field(..., description="When the sample was produced (UTC).")
    latitude: float = Field(..., description="Latitude in WGS 84 decimal degrees.")
    longitude: float = Field(..., description="Longitude in WGS 84 decimal degrees.")
    heading_deg: float | None = Field(
        default=None,
        description="Course over ground in degrees, 0 = north.",
    )
    speed_kmh: float = Field(..., description="Speed in km/h.")
    battery_soc_percent: float = Field(..., description="State of charge in percent.")
    battery_temperature_c: float = Field(..., description="Battery temperature in °C.")
    outside_temperature_c: float = Field(..., description="Ambient temperature in °C.")
    instantaneous_power_kw: float = Field(
        ...,
        description="Battery power in kW; negative while recuperating.",
    )
    energy_consumption_kwh_100km: float = Field(
        ...,
        description="Consumption over the sample window, kWh/100 km.",
    )
    estimated_range_km: float = Field(
        ...,
        description="Remaining range at the current consumption, in km.",
    )
    road_class: RoadClass = Field(..., description="Road class being driven on.")
    state: VehicleState = Field(..., description="What the vehicle is doing.")


class TelemetryPoint(ApiModel):
    """One sample of a vehicle's history, reduced to what a chart needs."""

    recorded_at: datetime = Field(..., description="Sample time (UTC).")
    latitude: float = Field(..., description="Latitude in WGS 84 decimal degrees.")
    longitude: float = Field(..., description="Longitude in WGS 84 decimal degrees.")
    speed_kmh: float = Field(..., description="Speed in km/h.")
    battery_soc_percent: float = Field(..., description="State of charge in percent.")
    energy_consumption_kwh_100km: float = Field(..., description="Consumption in kWh/100 km.")
    odometer_m: float = Field(..., description="Cumulative distance in metres.")


class VehicleDetail(VehicleSummary):
    """One vehicle with its physical profile, its current sample and its trip history."""

    battery_capacity_kwh: float = Field(..., description="Gross battery capacity in kWh.")
    usable_capacity_kwh: float = Field(..., description="Usable capacity in kWh.")
    nominal_consumption_kwh_100km: float = Field(
        ...,
        description="Reference consumption of the class, kWh/100 km.",
    )
    max_dc_power_kw: float = Field(..., description="Peak DC charging power in kW.")
    max_ac_power_kw: float = Field(..., description="Peak AC charging power in kW.")
    mass_kg: float = Field(..., description="Kerb mass in kg.")
    trips_total: int = Field(..., ge=0, description="Trips this vehicle has driven.")
    distance_total_m: float = Field(
        ...,
        ge=0.0,
        description="Distance summed over those trips, in metres.",
    )
    energy_total_kwh: float = Field(
        ...,
        ge=0.0,
        description="Energy summed over those trips, in kWh.",
    )
    latest: VehicleLive | None = Field(
        default=None,
        description="Newest telemetry sample; null if the vehicle has never reported.",
    )
    provenance: ProvenanceOut = Field(
        ...,
        description="Where the row came from — always `simulated` for a fleet vehicle.",
    )


class TripSummary(ApiModel):
    """One trip of one vehicle."""

    trip_id: str = Field(..., description="Stable trip identifier produced by the simulator.")
    vehicle_id: str = Field(..., description="Fleet identifier of the vehicle, e.g. `ATW-0042`.")
    route_id: UUID | None = Field(default=None, description="Corridor driven, when known.")
    route_slug: str | None = Field(
        default=None,
        description="Slug of that corridor, e.g. `frankfurt-stuttgart`.",
    )
    started_at: datetime = Field(..., description="Departure (UTC).")
    ended_at: datetime | None = Field(
        default=None,
        description="Arrival (UTC); null while the trip is running.",
    )
    start_soc_percent: float = Field(..., description="State of charge at departure, percent.")
    end_soc_percent: float | None = Field(
        default=None,
        description="State of charge on arrival, percent; null while running.",
    )
    distance_m: float = Field(..., ge=0.0, description="Distance driven so far, in metres.")
    energy_kwh: float = Field(..., description="Energy drawn from the battery so far, in kWh.")
    avg_consumption_kwh_100km: float | None = Field(
        default=None,
        description="Mean consumption over the trip; null before the first kilometre.",
    )
    state: VehicleState = Field(..., description="State of the vehicle on this trip.")


class TripSeriesPoint(ApiModel):
    """One point of a trip's SOC/speed series, positioned along the trip rather than in time."""

    recorded_at: datetime = Field(..., description="Sample time (UTC).")
    offset_km: float = Field(
        ...,
        ge=0.0,
        description="Distance from the start of the trip, in km — the x axis of the charts.",
    )
    speed_kmh: float = Field(..., description="Speed in km/h.")
    battery_soc_percent: float = Field(..., description="State of charge in percent.")
    energy_consumption_kwh_100km: float = Field(..., description="Consumption in kWh/100 km.")
    cumulative_energy_kwh: float = Field(..., description="Energy used since departure, in kWh.")
    latitude: float = Field(..., description="Latitude in WGS 84 decimal degrees.")
    longitude: float = Field(..., description="Longitude in WGS 84 decimal degrees.")


class TripDetail(TripSummary):
    """A trip with the series that show how it went."""

    model_code: str | None = Field(
        default=None,
        description="Vehicle profile the trip was driven with.",
    )
    route_name: str | None = Field(default=None, description="Human name of the corridor.")
    samples: int = Field(..., ge=0, description="Telemetry samples recorded for this trip.")
    series: list[TripSeriesPoint] = Field(
        default_factory=list,
        description=(
            "SOC, speed and consumption against distance, oldest first. Capped, and "
            "`samples` says how many the trip really has."
        ),
    )
    provenance: ProvenanceOut = Field(
        ...,
        description="Where the trip came from — always `simulated`.",
    )
