"""Alembic environment for AutoTwin DE.

Two things here are not boilerplate and are worth reading before changing them:

1. **The URL comes from settings, never from ``alembic.ini``.** A migration run and the
   application therefore cannot be pointed at different databases by accident.

2. **PostGIS owns objects in our database that we must not manage.** Installing the extension
   creates ``spatial_ref_sys``, ``geometry_columns``, ``geography_columns`` and the
   ``tiger``/``topology`` schemas. Without the filters below, ``--autogenerate`` cheerfully
   proposes dropping all of them, and applying that migration breaks PostGIS.
"""

from __future__ import annotations

from logging.config import fileConfig
from typing import Any

from sqlalchemy import Connection, pool
from sqlalchemy.engine import Engine, create_engine

from alembic import context
from autotwin_core.config import get_settings
from autotwin_core.db.base import Base

# Importing the models module is what registers every table on ``Base.metadata``.
# It looks unused to a linter; it is the entire point of this file.
from autotwin_core.db import models  # noqa: F401  # isort: skip

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = Base.metadata

# --------------------------------------------------------------------------------------
# PostGIS objects we must leave alone
# --------------------------------------------------------------------------------------

POSTGIS_TABLES: frozenset[str] = frozenset(
    {
        "spatial_ref_sys",
        "geometry_columns",
        "geography_columns",
        "raster_columns",
        "raster_overviews",
        # PostGIS Tiger geocoder, present in the postgis/postgis image.
        "addr",
        "addrfeat",
        "bg",
        "county",
        "county_lookup",
        "countysub_lookup",
        "cousub",
        "direction_lookup",
        "edges",
        "faces",
        "featnames",
        "geocode_settings",
        "geocode_settings_default",
        "loader_lookuptables",
        "loader_platform",
        "loader_variables",
        "pagc_gaz",
        "pagc_lex",
        "pagc_rules",
        "place",
        "place_lookup",
        "secondary_unit_lookup",
        "state",
        "state_lookup",
        "street_type_lookup",
        "tabblock",
        "tabblock20",
        "tract",
        "zcta5",
        "zip_lookup",
        "zip_lookup_all",
        "zip_lookup_base",
        "zip_state",
        "zip_state_loc",
    }
)

IGNORED_SCHEMAS: frozenset[str] = frozenset({"tiger", "tiger_data", "topology"})


def include_object(
    obj: Any,
    name: str | None,
    type_: str,
    reflected: bool,  # signature is fixed by Alembic
    compare_to: Any,
) -> bool:
    """Keep PostGIS's own objects out of autogenerated migrations."""
    schema = getattr(obj, "schema", None)
    if schema in IGNORED_SCHEMAS:
        return False
    if type_ == "table" and name in POSTGIS_TABLES:
        return False
    # Spatial indexes created by PostGIS itself on its own tables.
    if type_ == "index" and name is not None and name.startswith("idx_"):
        table = getattr(obj, "table", None)
        if table is not None and table.name in POSTGIS_TABLES:
            return False
    return True


def render_item(type_: str, obj: Any, autogen_context: Any) -> str | bool:
    """Render GeoAlchemy2 column types as importable expressions.

    Without this, autogenerate emits ``geoalchemy2.types.Geography()`` with no import and the
    generated migration fails at import time.
    """
    if type_ == "type" and obj.__class__.__module__.startswith("geoalchemy2"):
        autogen_context.imports.add("import geoalchemy2")
        return f"geoalchemy2.types.{obj.__class__.__name__}({_render_spatial_args(obj)})"
    return False


def _render_spatial_args(obj: Any) -> str:
    parts: list[str] = [
        f"geometry_type={obj.geometry_type!r}",
        f"srid={obj.srid!r}",
    ]
    # We declare every spatial index explicitly in the models, so GeoAlchemy2 must not add
    # a second one behind our back.
    parts.append("spatial_index=False")
    if getattr(obj, "nullable", True) is False:
        parts.append("nullable=False")
    return ", ".join(parts)


def _configure(connection: Connection | None = None, url: str | None = None) -> None:
    common: dict[str, Any] = {
        "target_metadata": target_metadata,
        "compare_type": True,
        "compare_server_default": True,
        "include_object": include_object,
        "render_item": render_item,
        "include_schemas": False,
        "version_table": "alembic_version",
        "transaction_per_migration": True,
    }
    if connection is not None:
        context.configure(connection=connection, **common)
    else:
        context.configure(
            url=url,
            literal_binds=True,
            dialect_opts={"paramstyle": "named"},
            **common,
        )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a database connection (``alembic upgrade head --sql``)."""
    _configure(url=get_settings().database_url_sync)
    with context.begin_transaction():
        context.run_migrations()


def _engine() -> Engine:
    return create_engine(
        get_settings().database_url_sync,
        poolclass=pool.NullPool,
        future=True,
    )


def run_migrations_online() -> None:
    """Apply migrations against a live database."""
    with _engine().connect() as connection:
        _configure(connection=connection)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
